.TH "decompress.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decompress.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStatus\fP \fBdecompress\fP (char *filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBStatus\fP decompress (char * filename)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
