.TH "HUFFMAN_CODE" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HUFFMAN_CODE
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <HUFFMAN_TABLE\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcode\fP"
.br
.ti -1c
.RI "uint8_t \fBlength\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t code"

.SS "uint8_t length"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
