.TH "HUFFMAN_TABLE.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HUFFMAN_TABLE.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'bitreader\&.h'\fP
.br
\fR#include 'node\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBHUFFMAN_CODE\fP"
.br
.ti -1c
.RI "struct \fBHuffmanEntry\fP"
.br
.ti -1c
.RI "struct \fBCanonicalCode\fP"
.br
.ti -1c
.RI "struct \fBHuffmanTree\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFAST_BITS\fP   9"
.br
.ti -1c
.RI "#define \fBFAST_SIZE\fP   (1 << \fBFAST_BITS\fP)"
.br
.ti -1c
.RI "#define \fBMAX_CODE_SYMBOLS\fP   286"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbuildCodeLookupTable\fP (\fBNode\fP *node, \fBHUFFMAN_CODE\fP *table, uint16_t current_code, int depth)"
.br
.ti -1c
.RI "void \fBbuildFastLookupTable\fP (const \fBHUFFMAN_CODE\fP *canonical_codes, int total_symbols, \fBHuffmanEntry\fP *lookup_table)"
.br
.ti -1c
.RI "uint16_t \fBdecode_symbol\fP (\fBBIT_READER\fP *reader, const \fBHuffmanTree\fP *tree)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FAST_BITS   9"

.SS "#define FAST_SIZE   (1 << \fBFAST_BITS\fP)"

.SS "#define MAX_CODE_SYMBOLS   286"

.SH "Function Documentation"
.PP 
.SS "void buildCodeLookupTable (\fBNode\fP * node, \fBHUFFMAN_CODE\fP * table, uint16_t current_code, int depth)\fR [extern]\fP"

.SS "void buildFastLookupTable (const \fBHUFFMAN_CODE\fP * canonical_codes, int total_symbols, \fBHuffmanEntry\fP * lookup_table)\fR [extern]\fP"

.SS "uint16_t decode_symbol (\fBBIT_READER\fP * reader, const \fBHuffmanTree\fP * tree)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
