.TH "LENGTH_CODE" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LENGTH_CODE
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <length\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBusSymbolID\fP"
.br
.ti -1c
.RI "int \fBiExtraBits\fP"
.br
.ti -1c
.RI "int \fBiExtraValue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int iExtraBits"

.SS "int iExtraValue"

.SS "unsigned short usSymbolID"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
