.TH "MinHeap" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinHeap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <node\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBiSize\fP"
.br
.ti -1c
.RI "int \fBiCapacity\fP"
.br
.ti -1c
.RI "\fBNode\fP ** \fBppnArray\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int iCapacity"

.SS "int iSize"

.SS "\fBNode\fP** ppnArray"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
