.TH "Node" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <node\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBiFrequency\fP"
.br
.ti -1c
.RI "unsigned short \fBusSymbol\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBpnLeft\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBpnRight\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int iFrequency"

.SS "struct \fBNode\fP* pnLeft"

.SS "struct \fBNode\fP* pnRight"

.SS "unsigned short usSymbol"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
