.TH "status.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
status.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStatus\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatusCode\fP { \fBCOMPRESSION_SUCCESS\fP, \fBCOMPRESSION_FAILED\fP, \fBCANT_OPEN_FILE\fP, \fBCANT_ALLOCATE_MEMORY\fP, \fBDECOMPRESS_SUCCESS\fP, \fBDECOMPRESS_FAILED\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBStatusCode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICOMPRESSION_SUCCESS \fP
.TP
\f(BICOMPRESSION_FAILED \fP
.TP
\f(BICANT_OPEN_FILE \fP
.TP
\f(BICANT_ALLOCATE_MEMORY \fP
.TP
\f(BIDECOMPRESS_SUCCESS \fP
.TP
\f(BIDECOMPRESS_FAILED \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
