.TH "Status" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Status
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <status\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBStatusCode\fP \fBcode\fP"
.br
.ti -1c
.RI "char * \fBmessage\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBStatusCode\fP code"

.SS "char* message"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
